spring:
  application:
    name: securityExam

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 4MB

  datasource:
    url: jdbc:mysql://localhost:3306/jpadb
    username: jpachill
    password: jpachill
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name : dosangwon
      password: 123123

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  tomcat:
    threads:
      min-spare: 10 # 항상 활성화되어 있는(idle) 스레드의 개수  항상 유지할 최소 대기 스레드 수
      max: 200 # Tomcat의 최대 스레드 수를 지정 즉 Tomcat이 동시에 처리할 수 있는 최대 요청 수 생성할 수 있는 스레드의 총 개수



#logging:
    #  level:
      #    org:
        #   springframework:
        #     security: TRACE
        #로그를 더 상세하게 찍어줘

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012